apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bot.name" . }}-nonebot-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: nonebot
  {{- if and .Values.ingress.key .Values.ingress.cert }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  {{- end }}
spec:
  {{- if and .Values.ingress.key .Values.ingress.cert }}
  tls:
    - hosts:
        - {{ required "tls host" .Values.ingress.host }}
      secretName: {{ include "bot.name" . }}-nonebot-tls
  {{- end }}
  rules:
    - {{- with .Values.ingress.host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bot.name" . }}-nonebot-service
                port:
                  name: nonebot

{{- /* http redirect to https */ -}}
{{- if and .Values.ingress.key .Values.ingress.cert }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bot.name" . }}-nonebot-redirect
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: nonebot
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: |-
      {{ .Release.Namespace }}-{{ include "bot.name" . }}-nonebot-redirect@kubernetescrd
spec:
  rules:
    - host: {{ default "*" .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bot.name" . }}-nonebot-service
                port:
                  name: nonebot
{{- end }}
