{{- if and .Values.ingress.key .Values.ingress.cert }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "bot.name" . }}-nonebot-redirect
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: nonebot
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
