{{- if and .Values.ingress.key .Values.ingress.cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bot.name" . }}-nonebot-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: nonebot
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.cert | b64enc }}
  tls.key: {{ .Values.ingress.key | b64enc }}
{{- end }}
