apiVersion: v1
kind: Service
metadata:
  name: {{ include "bot.name" . }}-nonebot-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: nonebot
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nonebot
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nonebot
      protocol: TCP
      name: nonebot
