apiVersion: v1
kind: Service
metadata:
  name: {{ include "bot.name" . }}-redis-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
