apiVersion: v1
kind: Service
metadata:
  name: {{ include "bot.name" . }}-postgres-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
